SKILL_CATEGORIES = {  # Not used
  'co': 'Cooking',
  'cs': 'Common Sense',
  'en': 'Endurance',
  'le': 'Leisure',
  'pa': 'Psi Ability',
  'pe': 'Performance',
  'se': 'Seafairing',
  'so': 'Social',
  'sp': 'Sports',
  'su': 'Survival',
  }

SKILLS = {
  'ac': 'Arts & Crafts',
  'ah': 'Animal Handling',
  'ar': 'Archery',
  'bb': 'Baseball',
  'cg': 'Card Games',
  'cpr': 'CPR',
  'db': 'Dodgeball',
  'em': 'Empathy',
  'fa': 'First Aid',
  'fh': 'Fishing',
  'fo': 'Foraging',
  'fr': 'Firebuilding',
  'in': 'Intuition',
  'kn': 'Knots',
  'la': 'Lacrosse',
  'ly': 'Lying',
  'mu': 'Music',
  'nv': 'Nacigation',
  'or': 'Originality',
  'pkr': 'Pk-Rockin\'',
  'pr': 'Presentation',
  'rc': 'Rock Climbing',
  'sa': 'Sailing',
  'suc': 'Stand Up Comedy',
  'sw': 'Swimming',
  'swg': 'Swag',
  'ta': 'Taste',
  'th': 'Theater',
  'tk': 'Telekenisis',
  'tp': 'Telepathy',
  }

STATS_SKILLS = {
  'Animal Handling': 0,
  'Archery': 0,
  'Arts & Crafts': 0,
  'Baseball': 0,
  'Card Games': 0,
  'Dodgeball': 0,
  'Empathy': 0,
  'Firebuilding': 0,
  'First Aid': 0,
  'Fishing': 0,
  'Foraging': 0,
  'Intuition': 0,
  'Lacrosse': 0,
  'Lying': 0,
  'Music': 0,
  'Navigation': 0,
  'Originality': 0,
  'Pk-Rockin\'': 0,
  'Presentation': 0,
  'Rock Climbing': 0,
  'Stand Up Comedy': 0,
  'Swag': 0,
  'Swimming': 0,
  'Taste': 0,
  'Telekenisis': 0,
  'Telepathy': 0,
  'Theater': 0,
  }

